/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cloudsample;
import cloudsample.LOA_Scheduler;
import cloudsample.utils.DatacenterCreator;
import cloudsample.utils.GenerateMatrices;
import java.util.Calendar;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import org.cloudbus.cloudsim.Cloudlet;
import org.cloudbus.cloudsim.Datacenter;
import org.cloudbus.cloudsim.Log;
import org.cloudbus.cloudsim.core.CloudSim;
import cloudsample.utils.Constants;
import java.io.IOException;
import PSO.PSO_Scheduler;
import javax.swing.WindowConstants;

/**
 *
 * @author agras
 */
public class NewJFrame extends javax.swing.JFrame {
public static int ct1,ct2,ct3,ct4,ct5,ct6;
public static int ms1,ms2,ms3,ms4,ms5,ms6;
public static int cs1,cs2,cs3,cs4,cs5,cs6;
public static int rt1,rt2,rt3,rt4,rt5,rt6;
public static int ut1,ut2,ut3,ut4,ut5,ut6;
public static int fed_no_of_tasks;
public static int c1_p1,c1_p2,c1_p3,c1_p4,c1_p5,c1_p6,c1_p7,c1_p8;
public static int c2_p1,c2_p2,c2_p3,c2_p4,c2_p5,c2_p6,c2_p7,c2_p8;
public static int c3_p1,c3_p2,c3_p3,c3_p4,c3_p5,c3_p6,c3_p7,c3_p8;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setBounds(0,0,2500,1500);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel22 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel23 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jButton14 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NO. OF TASKS");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 300, 180, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NO. OF DATA CENTERS");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 360, 290, 29);

        jTextField1.setColumns(15);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("Enter no. of tasks");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(440, 300, 306, 35);

        jTextField2.setColumns(15);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField2.setText("Enter no. of data centers");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField2);
        jTextField2.setBounds(440, 360, 306, 35);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("SET PARAMETERS");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(100, 870, 223, 37);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jInternalFrame1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1120, 270, 690, 650);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("OUTPUT");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(440, 870, 123, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VM SIZE");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 420, 110, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VM RAM");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 480, 110, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("VM MIPS");
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 540, 110, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("VM BW");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 600, 140, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NO. OF CPUs");
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 660, 170, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FILE SIZE");
        jInternalFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 730, 120, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("OUTPUT SIZE");
        jInternalFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 790, 170, 29);

        jTextField3.setColumns(15);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField3.setText("Enter the VM Size");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField3);
        jTextField3.setBounds(440, 420, 306, 35);

        jTextField4.setColumns(15);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField4.setText("Enter the VM RAM");
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField4);
        jTextField4.setBounds(440, 480, 306, 35);

        jTextField5.setColumns(15);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField5.setText("Enter the VM MIPS");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField5);
        jTextField5.setBounds(440, 540, 306, 35);

        jTextField6.setColumns(15);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField6.setText("Enter the VM BW");
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField6);
        jTextField6.setBounds(440, 600, 306, 35);

        jTextField7.setColumns(15);
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField7.setText("Enter the no of CPUs");
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField7);
        jTextField7.setBounds(440, 660, 306, 35);

        jTextField8.setColumns(15);
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField8.setText("Enter the file size");
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField8);
        jTextField8.setBounds(440, 730, 306, 35);

        jTextField9.setColumns(15);
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField9.setText("Enter the output size");
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField9FocusGained(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField9);
        jTextField9.setBounds(440, 790, 306, 35);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("10-100");
        jInternalFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(850, 300, 100, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("5-25");
        jInternalFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(850, 360, 70, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("5000-25000(MB)");
        jInternalFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(850, 420, 200, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("256-512(MB)");
        jInternalFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(850, 480, 160, 29);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("150-500");
        jInternalFrame1.getContentPane().add(jLabel14);
        jLabel14.setBounds(850, 540, 120, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("500-5000(MB/sec)");
        jInternalFrame1.getContentPane().add(jLabel15);
        jLabel15.setBounds(850, 600, 220, 29);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("1-4");
        jInternalFrame1.getContentPane().add(jLabel16);
        jLabel16.setBounds(860, 660, 40, 29);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("100-500(MB)");
        jInternalFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(850, 730, 150, 29);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("200-500(MB)");
        jInternalFrame1.getContentPane().add(jLabel18);
        jLabel18.setBounds(850, 790, 138, 29);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("NON CLASSICAL OPTIMISATION OF DYNAMIC RESOURCE ");
        jInternalFrame1.getContentPane().add(jLabel21);
        jLabel21.setBounds(80, 20, 1760, 100);
        jInternalFrame1.getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(850, 870, 180, 40);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("PROVISIONING IN FEDERATED CLOUD");
        jInternalFrame1.getContentPane().add(jLabel44);
        jLabel44.setBounds(370, 130, 1190, 73);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jInternalFrame1.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(1228, 319, 577, 455);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\agras\\Desktop\\cloudProj\\CloudSample\\2.jpg")); // NOI18N
        jLabel20.setText("jLabel20");
        jInternalFrame1.getContentPane().add(jLabel20);
        jLabel20.setBounds(0, -20, 2010, 1030);

        jTabbedPane1.addTab("CLOUD MULTI OBJECTIVES", jInternalFrame1);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("COMPLETION TIME VS NO. OF TASKS");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton3);
        jButton3.setBounds(676, 297, 610, 60);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("MAKESPAN VS NO. OF TASKS");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton4);
        jButton4.setBounds(680, 400, 610, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("COST VS NO. OF TASKS");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton5);
        jButton5.setBounds(680, 510, 610, 60);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("AVERAGE RESPONSE TIME VS NO. OF TASKS");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton6);
        jButton6.setBounds(680, 620, 610, 60);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("AVERAGE RESPONSE TIME VS NO. OF TASKS");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton7);
        jButton7.setBounds(680, 730, 610, 60);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("GENERATE GRAPHS");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton8);
        jButton8.setBounds(676, 43, 610, 80);
        jInternalFrame2.getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(676, 151, 610, 90);

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\agras\\Desktop\\cloudProj\\CloudSample\\3.jpg")); // NOI18N
        jLabel22.setText("jLabel22");
        jInternalFrame2.getContentPane().add(jLabel22);
        jLabel22.setBounds(-30, -90, 2080, 1140);

        jTabbedPane1.addTab("BAR CHART", jInternalFrame2);

        jInternalFrame3.setVisible(true);
        jInternalFrame3.getContentPane().setLayout(null);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("COMPLETION TIME VS NO. OF TASKS");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton9);
        jButton9.setBounds(676, 297, 610, 60);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setText("MAKESPAN VS NO. OF TASKS");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton10);
        jButton10.setBounds(680, 400, 610, 60);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setText("COST VS NO. OF TASKS");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton11);
        jButton11.setBounds(680, 510, 610, 60);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setText("AVERAGE RESPONSE TIME VS NO. OF TASKS");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton12);
        jButton12.setBounds(680, 620, 610, 60);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton13.setText("AVERAGE RESPONSE TIME VS NO. OF TASKS");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton13);
        jButton13.setBounds(680, 730, 610, 60);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton15.setText("GENERATE GRAPHS");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton15);
        jButton15.setBounds(676, 43, 610, 80);
        jInternalFrame3.getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(676, 151, 610, 90);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\agras\\Desktop\\cloudProj\\CloudSample\\4.png")); // NOI18N
        jLabel23.setText("jLabel23");
        jInternalFrame3.getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 2120, 1120);

        jTabbedPane1.addTab("LINE CHART", jInternalFrame3);

        jInternalFrame4.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrame4.setVisible(true);
        jInternalFrame4.getContentPane().setLayout(null);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CLOUD 1");
        jInternalFrame4.getContentPane().add(jLabel26);
        jLabel26.setBounds(490, 170, 180, 29);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("VM RAM");
        jInternalFrame4.getContentPane().add(jLabel29);
        jLabel29.setBounds(120, 410, 110, 29);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("VM MIPS");
        jInternalFrame4.getContentPane().add(jLabel30);
        jLabel30.setBounds(120, 500, 110, 29);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("VM BW");
        jInternalFrame4.getContentPane().add(jLabel31);
        jLabel31.setBounds(120, 580, 140, 29);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("OUTPUT SIZE");
        jInternalFrame4.getContentPane().add(jLabel34);
        jLabel34.setBounds(120, 820, 190, 29);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("FILE SIZE");
        jInternalFrame4.getContentPane().add(jLabel35);
        jLabel35.setBounds(120, 740, 120, 29);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("NO. OF CPUs");
        jInternalFrame4.getContentPane().add(jLabel36);
        jLabel36.setBounds(120, 660, 170, 29);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("VM SIZE");
        jInternalFrame4.getContentPane().add(jLabel40);
        jLabel40.setBounds(120, 330, 110, 29);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("NO. OF DATA CENTERS");
        jInternalFrame4.getContentPane().add(jLabel41);
        jLabel41.setBounds(120, 250, 280, 29);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("CLOUD 2");
        jInternalFrame4.getContentPane().add(jLabel42);
        jLabel42.setBounds(860, 170, 180, 29);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("CLOUD 3");
        jInternalFrame4.getContentPane().add(jLabel51);
        jLabel51.setBounds(1230, 170, 180, 29);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("NO. OF TASKS");
        jInternalFrame4.getContentPane().add(jLabel53);
        jLabel53.setBounds(490, 80, 180, 29);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("10-100");
        jInternalFrame4.getContentPane().add(jLabel19);
        jLabel19.setBounds(1240, 80, 110, 29);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("5-25");
        jInternalFrame4.getContentPane().add(jLabel25);
        jLabel25.setBounds(1670, 250, 90, 29);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("256-512(MB)");
        jInternalFrame4.getContentPane().add(jLabel28);
        jLabel28.setBounds(1660, 410, 150, 29);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("150-500");
        jInternalFrame4.getContentPane().add(jLabel32);
        jLabel32.setBounds(1660, 490, 120, 29);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("500-5000(MB/sec)");
        jInternalFrame4.getContentPane().add(jLabel33);
        jLabel33.setBounds(1660, 570, 220, 40);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("1-4");
        jInternalFrame4.getContentPane().add(jLabel37);
        jLabel37.setBounds(1670, 650, 40, 29);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("100-500(MB)");
        jInternalFrame4.getContentPane().add(jLabel38);
        jLabel38.setBounds(1670, 730, 160, 29);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("200-500(MB)");
        jInternalFrame4.getContentPane().add(jLabel39);
        jLabel39.setBounds(1670, 820, 138, 29);

        jTextField10.setColumns(15);
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField10.setText("Enter no. of tasks");
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField10FocusGained(evt);
            }
        });
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField10);
        jTextField10.setBounds(860, 80, 306, 35);

        jTextField11.setColumns(15);
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField11.setText("Enter no. of data centers");
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField11FocusGained(evt);
            }
        });
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField11);
        jTextField11.setBounds(1230, 250, 306, 35);

        jTextField12.setColumns(15);
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField12.setText("Enter the VM Size");
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField12FocusGained(evt);
            }
        });
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField12);
        jTextField12.setBounds(1230, 330, 306, 35);

        jTextField13.setColumns(15);
        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField13.setText("Enter the VM RAM");
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField13FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField13);
        jTextField13.setBounds(860, 410, 306, 35);

        jTextField14.setColumns(15);
        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField14.setText("Enter the VM MIPS");
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField14FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField14);
        jTextField14.setBounds(860, 490, 306, 35);

        jTextField15.setColumns(15);
        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField15.setText("Enter the VM BW");
        jTextField15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField15FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField15);
        jTextField15.setBounds(860, 570, 306, 35);

        jTextField16.setColumns(15);
        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField16.setText("Enter the no of CPUs");
        jTextField16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField16FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField16);
        jTextField16.setBounds(860, 650, 306, 35);

        jTextField17.setColumns(15);
        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField17.setText("Enter the file size");
        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField17FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField17);
        jTextField17.setBounds(860, 730, 306, 35);

        jTextField18.setColumns(15);
        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField18.setText("Enter the output size");
        jTextField18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField18FocusGained(evt);
            }
        });
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField18);
        jTextField18.setBounds(860, 820, 306, 35);

        jTextField20.setColumns(15);
        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField20.setText("Enter no. of data centers");
        jTextField20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField20FocusGained(evt);
            }
        });
        jTextField20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField20MouseClicked(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField20);
        jTextField20.setBounds(860, 250, 306, 35);

        jTextField21.setColumns(15);
        jTextField21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField21.setText("Enter the VM Size");
        jTextField21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField21FocusGained(evt);
            }
        });
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField21);
        jTextField21.setBounds(860, 330, 306, 35);

        jTextField22.setColumns(15);
        jTextField22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField22.setText("Enter the VM RAM");
        jTextField22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField22FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField22);
        jTextField22.setBounds(1230, 410, 306, 35);

        jTextField23.setColumns(15);
        jTextField23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField23.setText("Enter the VM MIPS");
        jTextField23.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField23FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField23);
        jTextField23.setBounds(1230, 490, 306, 35);

        jTextField24.setColumns(15);
        jTextField24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField24.setText("Enter the VM BW");
        jTextField24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField24FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField24);
        jTextField24.setBounds(1230, 570, 306, 35);

        jTextField25.setColumns(15);
        jTextField25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField25.setText("Enter the no of CPUs");
        jTextField25.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField25FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField25);
        jTextField25.setBounds(1230, 650, 306, 35);

        jTextField26.setColumns(15);
        jTextField26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField26.setText("Enter the file size");
        jTextField26.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField26FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField26);
        jTextField26.setBounds(1230, 730, 306, 35);

        jTextField27.setColumns(15);
        jTextField27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField27.setText("Enter the output size");
        jTextField27.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField27FocusGained(evt);
            }
        });
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField27);
        jTextField27.setBounds(1230, 820, 306, 35);

        jTextField29.setColumns(15);
        jTextField29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField29.setText("Enter no. of data centers");
        jTextField29.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField29FocusGained(evt);
            }
        });
        jTextField29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField29MouseClicked(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField29);
        jTextField29.setBounds(490, 250, 306, 35);

        jTextField30.setColumns(15);
        jTextField30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField30.setText("Enter the VM Size");
        jTextField30.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField30FocusGained(evt);
            }
        });
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField30);
        jTextField30.setBounds(490, 330, 306, 35);

        jTextField31.setColumns(15);
        jTextField31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField31.setText("Enter the VM RAM");
        jTextField31.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField31FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField31);
        jTextField31.setBounds(490, 410, 306, 35);

        jTextField32.setColumns(15);
        jTextField32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField32.setText("Enter the VM MIPS");
        jTextField32.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField32FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField32);
        jTextField32.setBounds(490, 490, 306, 35);

        jTextField33.setColumns(15);
        jTextField33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField33.setText("Enter the VM BW");
        jTextField33.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField33FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField33);
        jTextField33.setBounds(490, 570, 306, 35);

        jTextField34.setColumns(15);
        jTextField34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField34.setText("Enter the no of CPUs");
        jTextField34.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField34FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField34);
        jTextField34.setBounds(490, 650, 306, 35);

        jTextField35.setColumns(15);
        jTextField35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField35.setText("Enter the file size");
        jTextField35.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField35FocusGained(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField35);
        jTextField35.setBounds(490, 730, 306, 35);

        jTextField36.setColumns(15);
        jTextField36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField36.setText("Enter the output size");
        jTextField36.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField36FocusGained(evt);
            }
        });
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField36);
        jTextField36.setBounds(490, 820, 306, 35);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("5000-25000(MB)");
        jInternalFrame4.getContentPane().add(jLabel24);
        jLabel24.setBounds(1660, 330, 190, 29);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton16.setText("SET PARAMETERS");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton16);
        jButton16.setBounds(857, 895, 310, 50);

        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Users\\agras\\Desktop\\cloudProj\\CloudSample\\5.jpg")); // NOI18N
        jLabel43.setText("jLabel43");
        jInternalFrame4.getContentPane().add(jLabel43);
        jLabel43.setBounds(0, 0, 2000, 1020);

        jTabbedPane1.addTab("FEDERATED CLOUD INPUT", jInternalFrame4);

        jInternalFrame5.setVisible(true);
        jInternalFrame5.getContentPane().setLayout(null);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton14.setText("OUTPUT");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jInternalFrame5.getContentPane().add(jButton14);
        jButton14.setBounds(890, 90, 135, 51);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jInternalFrame5.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(461, 205, 1030, 610);

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\agras\\Desktop\\cloudProj\\CloudSample\\6.jpg")); // NOI18N
        jLabel27.setText("jLabel27");
        jInternalFrame5.getContentPane().add(jLabel27);
        jLabel27.setBounds(-130, -20, 2060, 1030);

        jTabbedPane1.addTab("FEDERATED CLOUD OUTPUT", jInternalFrame5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
  public void fill1() 
    { 
        int i = 0; 
        try { 
            while (i <= 100) { 
                // fill the menu bar 
                jProgressBar1.setValue(i); 
  
                // delay the thread 
                //Thread.sleep(10); 
                i += 20; 
            } 
        } 
        catch (Exception e) { 
        } 
    }  
    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {                                      
       // set initial value 
        jProgressBar1.setValue(0); 
  
        jProgressBar1.setStringPainted(true);
        
        fill1();
        
        Constants.NO_OF_TASKS=25;
        LOA_Scheduler loa1=new LOA_Scheduler();
        PSO_Scheduler pso1=new PSO_Scheduler();
        try
        {   
            loa1.loa_run();
            ct1=(int)loa1.mxFinishTime;
            ms1=(int)loa1.maxActualTime;
            cs1=(int)loa1.cost;
            rt1=(int)loa1.avg;
            ut1=(int)loa1.rut;
            pso1.pso_run();
            ct2=(int)pso1.mxFinishTime;
            ms2=(int)pso1.maxActualTime;
            cs2=(int)pso1.cost;
            rt2=(int)pso1.avg;
            ut2=(int)pso1.rut;
        }
        catch(IOException e)
        {
            System.out.println(""+e);
        }
        Constants.NO_OF_TASKS=50;
        LOA_Scheduler loa2=new LOA_Scheduler();
        PSO_Scheduler pso2=new PSO_Scheduler();
        try
        {   
            loa2.loa_run();
            ct3=(int)loa2.mxFinishTime;
            ms3=(int)loa2.maxActualTime;
            cs3=(int)loa2.cost;
            rt3=(int)loa2.avg;
            ut3=(int)loa2.rut;
            pso2.pso_run();
            ct4=(int)pso2.mxFinishTime;
            ms4=(int)pso2.maxActualTime;
            cs4=(int)pso2.cost;
            rt4=(int)pso2.avg;
            ut4=(int)pso2.rut;
            
        }
        catch(IOException e)
        {
            System.out.println(""+e);
        }
        Constants.NO_OF_TASKS=75;
        LOA_Scheduler loa3=new LOA_Scheduler();
        PSO_Scheduler pso3=new PSO_Scheduler();
        try
        {   
            loa3.loa_run();
            ct5=(int)loa3.mxFinishTime;
            ms5=(int)loa3.maxActualTime;
            cs5=(int)loa3.cost;
            rt5=(int)loa3.avg;
            ut5=(int)loa3.rut;
            pso3.pso_run();
            ct6=(int)pso3.mxFinishTime;
            ms6=(int)pso3.maxActualTime;
            cs6=(int)pso3.cost;
            rt6=(int)pso3.avg;
            ut6=(int)pso3.rut;
        }
        catch(IOException e)
        {
            System.out.println(""+e);
        }
    }                                     

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        try{
      
      BarChartExample example=new BarChartExample("Bar Chart 5","Average Resource Utilization Vs No of Tasks","Average Resource Utilization",ut1,ut2,ut3,ut4,ut5,ut6); 
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                     

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
         try{
      
      BarChartExample example=new BarChartExample("Bar Chart 4","Average Response Time Vs No of Tasks","Average Response Time",rt1,rt2,rt3,rt4,rt5,rt6); 
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                     

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        try{
      
      BarChartExample example=new BarChartExample("Bar Chart 3","Cost Vs No of Tasks","Cost",cs1,cs2,cs3,cs4,cs5,cs6); 
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                     

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
         try{
      
      BarChartExample example=new BarChartExample("Bar Chart 2","Makespan Vs No of Tasks","Makespan",ms1,ms2,ms3,ms4,ms5,ms6); 
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                     

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
try{
      
      BarChartExample example=new BarChartExample("Bar Chart 1","Completion Time Vs No of Tasks","Completion Time",ct1,ct2,ct3,ct4,ct5,ct6); 
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                     

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField9FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField9.setText("");
    }                                       

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField8.setText("");
    }                                       

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField7.setText("");
    }                                       

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField6.setText("");
    }                                       

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField5.setText("");
    }                                       

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField4.setText("");
    }                                       

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField3.setText("");
    }                                       

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
public void fill2() 
    { 
        int i = 0; 
        try { 
            while (i <= 100) { 
                // fill the menu bar 
                jProgressBar2.setValue(i); 
  
                // delay the thread 
                //Thread.sleep(10); 
                i += 20; 
            } 
        } 
        catch (Exception e) { 
        } 
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:

        // set initial value 
        jProgressBar2.setValue(0); 
  
        jProgressBar2.setStringPainted(true);
        
       fill2();
       LOA_Scheduler loa=new LOA_Scheduler();
        try
        {   
            loa.loa_run();
            
        }
        catch(IOException e)
        {
            System.out.println(""+e);
        }
         
        jTextArea1.setText("Completion Time: "+loa.mxFinishTime);
        jTextArea1.append("\n makespan:  "+loa.maxActualTime);
        jTextArea1.append("\n Cost of VMs (0.001,0.015,0.002,0.005,0.001) : Rs "+loa.cost);
        jTextArea1.append("\n Average Response Time(seconds): "+loa.avg);
        jTextArea1.append("\n Average Resource Utilization: "+loa.rut);
        jTextArea1.append("\n\n");
        jTextArea1.append("");

    }                                     

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:

        jTextArea1.setText("\n Initial Constant values:");
        jTextArea1.append("\n no of tasks= "+Constants.NO_OF_TASKS);
        jTextArea1.append("\n no of data centers = "+Constants.NO_OF_DATA_CENTERS);
        jTextArea1.append("\n VM size = "+Constants.VM_SIZE);
        jTextArea1.append("\n VM RAM = "+Constants.VM_RAM);
        jTextArea1.append("\n VM MIPS = "+Constants.VM_MIPS);
        jTextArea1.append("\n VM Bandwidth = "+Constants.VM_BW);
        jTextArea1.append("\n VM CPUs = "+Constants.VM_CPUS);
        jTextArea1.append("\n VM File Size = "+Constants.FILE_SIZE);
        jTextArea1.append("\n VM Output Size = "+Constants.OUTPUT_SIZE);
        
        Constants.NO_OF_TASKS=Integer.parseInt(jTextField1.getText());
        Constants.NO_OF_DATA_CENTERS=Integer.parseInt(jTextField2.getText());
        Constants.VM_SIZE=Integer.parseInt(jTextField3.getText());
        Constants.VM_RAM=Integer.parseInt(jTextField4.getText());
        Constants.VM_MIPS=Integer.parseInt(jTextField5.getText());
        Constants.VM_BW=Integer.parseInt(jTextField6.getText());
        Constants.VM_CPUS=Integer.parseInt(jTextField7.getText());
        Constants.FILE_SIZE=Integer.parseInt(jTextField8.getText());
        Constants.OUTPUT_SIZE=Integer.parseInt(jTextField9.getText());
        
        jTextArea1.append("\n\n Fetched Constant values");
        jTextArea1.append("\n no of tasks= "+Constants.NO_OF_TASKS);
        jTextArea1.append("\n no of data centers = "+Constants.NO_OF_DATA_CENTERS);
        jTextArea1.append("\n VM size = "+Constants.VM_SIZE);
        jTextArea1.append("\n VM RAM = "+Constants.VM_RAM);
        jTextArea1.append("\n VM MIPS = "+Constants.VM_MIPS);
        jTextArea1.append("\n VM Bandwidth = "+Constants.VM_BW);
        jTextArea1.append("\n VM CPUs = "+Constants.VM_CPUS);
        jTextArea1.append("\n VM File Size = "+Constants.FILE_SIZE);
        jTextArea1.append("\n VM Output Size = "+Constants.OUTPUT_SIZE);

    }                                     

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        jTextField2.setText("");
    }                                        

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField2.setText("");
    }                                       

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        jTextField1.setText("");
    }                                        

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        jTextField1.setText("");
    }                                       

    private void jTextField10FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        jTextField10.setText("");
    }                                         

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jTextField12FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField13FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField14FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField15FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField16FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField17FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField18FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField20FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField20MouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jTextField21FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField22FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField23FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField24FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField25FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField26FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField27FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField29FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField29MouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        jTextField29.setText("");
    }                                         

    private void jTextField30FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField31FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField32FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField33FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField34FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField35FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField36FocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        try{
      
     LineChartExample example = new LineChartExample("Line Chart 1","Completion Time Vs No of Tasks","Completion Time",ct1,ct2,ct3,ct4,ct5,ct6);  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);   
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                     

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        try{
      
     LineChartExample example = new LineChartExample("Line Chart 2","Makespan Vs No of Tasks","Makespan",ms1,ms2,ms3,ms4,ms5,ms6);  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);   
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                      

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
           try{
      
     LineChartExample example = new LineChartExample("Line Chart 3","Cost Vs No of Tasks","Cost",cs1,cs2,cs3,cs4,cs5,cs6);  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);   
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                      

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
               try{
      
     LineChartExample example = new LineChartExample("Line Chart 4","Average Response Time Vs No of Tasks","Average Response Time",rt1,rt2,rt3,rt4,rt5,rt6);  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);   
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                      

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        try{
      
     LineChartExample example = new LineChartExample("Line Chart 5","Average Resource Utilization Vs No of Tasks","Average Resource Utilization",ut1,ut2,ut3,ut4,ut5,ut6);  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);   
      
        }
        catch(Exception e)
        {
         System.out.println(""+e);   
        }
    }                                      
      
    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        // set initial value 
        jProgressBar1.setValue(0); 
  
        jProgressBar1.setStringPainted(true);
        
        fill1();
        
        Constants.NO_OF_TASKS=25;
        LOA_Scheduler loa1=new LOA_Scheduler();
        PSO_Scheduler pso1=new PSO_Scheduler();
        try
        {   
            loa1.loa_run();
            ct1=(int)loa1.mxFinishTime;
            ms1=(int)loa1.maxActualTime;
            cs1=(int)loa1.cost;
            rt1=(int)loa1.avg;
            ut1=(int)loa1.rut;
            pso1.pso_run();
            ct2=(int)pso1.mxFinishTime;
            ms2=(int)pso1.maxActualTime;
            cs2=(int)pso1.cost;
            rt2=(int)pso1.avg;
            ut2=(int)pso1.rut;
        }
        catch(IOException e)
        {
            System.out.println(""+e);
        }
        Constants.NO_OF_TASKS=50;
        LOA_Scheduler loa2=new LOA_Scheduler();
        PSO_Scheduler pso2=new PSO_Scheduler();
        try
        {   
            loa2.loa_run();
            ct3=(int)loa2.mxFinishTime;
            ms3=(int)loa2.maxActualTime;
            cs3=(int)loa2.cost;
            rt3=(int)loa2.avg;
            ut3=(int)loa2.rut;
            pso2.pso_run();
            ct4=(int)pso2.mxFinishTime;
            ms4=(int)pso2.maxActualTime;
            cs4=(int)pso2.cost;
            rt4=(int)pso2.avg;
            ut4=(int)pso2.rut;
            
        }
        catch(IOException e)
        {
            System.out.println(""+e);
        }
        Constants.NO_OF_TASKS=75;
        LOA_Scheduler loa3=new LOA_Scheduler();
        PSO_Scheduler pso3=new PSO_Scheduler();
        try
        {   
            loa3.loa_run();
            ct5=(int)loa3.mxFinishTime;
            ms5=(int)loa3.maxActualTime;
            cs5=(int)loa3.cost;
            rt5=(int)loa3.avg;
            ut5=(int)loa3.rut;
            pso3.pso_run();
            ct6=(int)pso3.mxFinishTime;
            ms6=(int)pso3.maxActualTime;
            cs6=(int)pso3.cost;
            rt6=(int)pso3.avg;
            ut6=(int)pso3.rut;
        }
        catch(IOException e)
        {
            System.out.println(""+e);
        }
    }                                      

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        
        fed_no_of_tasks=Integer.parseInt(jTextField10.getText());
        c1_p1=Integer.parseInt(jTextField29.getText());
        c1_p2=Integer.parseInt(jTextField30.getText());
        c1_p3=Integer.parseInt(jTextField31.getText());
        c1_p4=Integer.parseInt(jTextField32.getText());
        c1_p5=Integer.parseInt(jTextField33.getText());
        c1_p6=Integer.parseInt(jTextField34.getText());
        c1_p7=Integer.parseInt(jTextField35.getText());
        c1_p8=Integer.parseInt(jTextField36.getText());
        
        c2_p1=Integer.parseInt(jTextField20.getText());
        c2_p2=Integer.parseInt(jTextField21.getText());
        c2_p3=Integer.parseInt(jTextField13.getText());
        c2_p4=Integer.parseInt(jTextField14.getText());
        c2_p5=Integer.parseInt(jTextField15.getText());
        c2_p6=Integer.parseInt(jTextField16.getText());
        c2_p7=Integer.parseInt(jTextField17.getText());
        c2_p8=Integer.parseInt(jTextField18.getText());
        
        c3_p1=Integer.parseInt(jTextField11.getText());
        c3_p2=Integer.parseInt(jTextField12.getText());
        c3_p3=Integer.parseInt(jTextField22.getText());
        c3_p4=Integer.parseInt(jTextField23.getText());
        c3_p5=Integer.parseInt(jTextField24.getText());
        c3_p6=Integer.parseInt(jTextField25.getText());
        c3_p7=Integer.parseInt(jTextField26.getText());
        c3_p8=Integer.parseInt(jTextField27.getText());
        System.out.println(""+fed_no_of_tasks);
        System.out.println(""+c1_p1+" "+c1_p2+" "+c1_p3+" "+c1_p4+" "+c1_p5+" "+c1_p6+" "+c1_p7+" "+c1_p8);
        System.out.println(c2_p1+" "+c2_p2+" "+c2_p3+" "+c2_p4+" "+c2_p5+" "+c2_p6+" "+c2_p7+" "+c2_p8);
        System.out.println(c3_p1+" "+c3_p2+" "+c3_p3+" "+c3_p4+" "+c3_p5+" "+c3_p6+" "+c3_p7+" "+c3_p8);
    }                                      

    public static void frame_run() {
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration                   
}
